CREATE TABLE regions(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE users(
id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
region BIGINT NOT NULL,
role VARCHAR(40) NOT NULL,
FOREIGN KEY(region) REFERENCES regions(id)
);

CREATE TABLE posts(
id BIGSERIAL PRIMARY KEY,
content VARCHAR(255) NOT NULL,
created TIMESTAMP NOT NULL,
updated TIMESTAMP,
user_id BIGINT,
FOREIGN KEY(user_id) REFERENCES users(id)
);