language: java
services:
- postgresql
addons:
 postgresql: '10'
 apt:
  packages:
   - postgresql-10
   - postgresql-client-10
env:
 global:
  - PGPORT=5432
  - PGUSER=postgres
before_script:
- psql -c 'create database hibernate;' -U postgres